<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="RSoft-pc" failures="1" tests="1" name="testCases.TC_004_SF_ResponseValidation" time="61.766" errors="0" timestamp="2023-09-27T17:35:03 IST" skipped="0">
  <testcase classname="testCases.TC_004_SF_ResponseValidation" name="Test_Response_Val" time="61.766">
    <failure message="The following asserts failed:
	Phone Number Control Answer expected [1234567890] but found [+91 1234567890],
	Appointment Control Answer expected [01:00 PM - 01:29 PM Date : 27/09/2023] but found [Appointment Date : 27/09/2023, Time : [ 01:00 PM to 01:29 PM ]],
	MultiChoice Control Answer expected [Agree,DisAgree] but found [Strongly Agree, Agree, DisAgree],
	Range Control Answer expected [50] but found [Rs51/-],
	FileUpload Control Answer expected [D:\\NewFile.txt] but found [formshow_27092023_122728.txt],
	Link Control Answer expected [Message Us] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Phone Number Control Answer expected [1234567890] but found [+91 1234567890],
Appointment Control Answer expected [01:00 PM - 01:29 PM Date : 27/09/2023] but found [Appointment Date : 27/09/2023, Time : [ 01:00 PM to 01:29 PM ]],
MultiChoice Control Answer expected [Agree,DisAgree] but found [Strongly Agree, Agree, DisAgree],
Range Control Answer expected [50] but found [Rs51/-],
FileUpload Control Answer expected [D:\\NewFile.txt] but found [formshow_27092023_122728.txt],
Link Control Answer expected [Message Us] but found []
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at testCases.TC_004_SF_ResponseValidation.Test_Response_Val(TC_004_SF_ResponseValidation.java:154)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Test_Response_Val -->
</testsuite> <!-- testCases.TC_004_SF_ResponseValidation -->
